---
- name: test if git_username is set correctly
  assert:
    that:
      - git_username | length > 0
    quiet: yes
  when:
    - git_username is defined

- name: test if git_groupname is set correctly
  assert:
    that:
      - git_groupname | length > 0
    quiet: yes
  when:
    - git_groupname is defined

- name: test if git_user_email is set correctly
  assert:
    that:
      - git_user_email | length > 0
    quiet: yes
  when:
    - git_user_email is defined

- name: test if git_user_name is set correctly
  assert:
    that:
      - git_user_name | length > 0
    quiet: yes
  when:
    - git_user_name is defined

- name: test if git_repository_destination is set correctly
  assert:
    that:
      - git_repository_destination is defined
      - git_repository_destination | length > 0
    quiet: yes

- name: test if git_force is set correctly
  assert:
    that:
      - git_force is defined
      - git_force is boolean
    quiet: yes

- name: test if git_repositories is set correctly
  assert:
    that:
      - git_repositories | length > 0
      - git_repositories is iterable
    quiet: yes
  when:
    - git_repositories is defined

- name: test if item in git_repositories is set correctly
  assert:
    that:
      - item.repo is defined
      - item.repo | length > 0
      - item.dest is defined
      - item.dest | length > 0
    quiet: yes
  loop: "{{ git_repositories }}"
  loop_control:
    label: "{{ item.repo }}"
  when:
    - git_repositories is defined

- name: test if item in git_repositories with version is set correctly
  assert:
    that:
      - item.version | length > 0
    quiet: yes
  when:
    - git_repositories is defined
    - item.version is defined

- name: test if item in git_repositories with force is set correctly
  assert:
    that:
      - item.version is boolean
    quiet: yes
  when:
    - git_repositories is defined
    - item.force is defined
